name: PR workflow handler

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-rules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, stg, prod]
    environment: ${{ matrix.env }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install requirements
        run: pip install -r requirements.txt

    #   - name: Install cfn-guard
    #     run: |
    #       curl -sS -L https://github.com/aws-cloudformation/cloudformation-guard/releases/latest/download/cfn-guard-linux -o cfn-guard
    #       chmod +x cfn-guard
    #       sudo mv cfn-guard /usr/local/bin/cfn-guard

      - name: Install cfn-guard
        run: |
            curl -sSL https://github.com/aws-cloudformation/cloudformation-guard/releases/download/2.1.1/cfn-guard-linux-2.1.1 -o cfn-guard
            chmod +x cfn-guard
            sudo mv cfn-guard /usr/local/bin/cfn-guard
    

      

      - name: Run cfn-guard tests
        run: python cfnguard/tests.py

    #   - name: Run tests (skip if not present)
    #     run: |
    #        if [ -f tests.py ]; then python3 tests.py; else echo "tests.py not found, skipping."; fi

