name: PR workflow handler

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-rules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, stg, prod]
    environment: ${{ matrix.env }}
    steps:
      - name: Setup the pipeline
        uses: SEC-OIT-ACES-ACTIONS/pipeline-setup@main
        with:
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          target_lifecycle: ${{ vars.TARGET_LIFECYCLE }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Install cfn-guard
        run: |
          curl -sS https://nexus-repo.cicd.prod.it-cuse1.aces.sec.gov/repository/ccoe-sharedservices-raw-dev/cfn-guard-v3ll-x86_64-ubuntu-latest.tar.gz -o cfn-guard.tar.gz
          tar -xzf cfn-guard.tar.gz
          sudo mv cfn-guard-v3ll-x86_64-ubuntu-latest/cfn-guard /usr/local/bin/cfn-guard

      - name: Run tests
        run: python3 tests.py
